### ISSUE TITLE
New enhancement to add tags upon execution

### ISSUE THREAD

**Issue by dtzar** [actions/add-to-project#120]
The current code is a filter to only add the issue to the project when those labels are detected.
```
          labeled: bug, needs-triage
          label-operator: OR
```
I would like to see a feature where you can have the task add new tags with whatever label(s) you desire upon execution.  For instance, something like `add-label`:

```
on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/<orgName>/projects/<projectNumber>
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          add-label: needs-triage
```
