### ISSUE TITLE
Workflow not running on PRs labeled by other GHA

### ISSUE THREAD

**Issue by mchelen-gov** [actions/add-to-project#121]
## Summary
The `add-to-project` workflow is not running when a PR is labeled by another Github Action.

## Reproduction steps
1. Configure https://github.com/actions/add-to-project to automatically add Pull Request with label `foo` to a project
2. Configure a GHA such as https://github.com/actions/labeler to automatically label Pull Requests with `foo`
3. Open a pull request
4. PR will automatically be labeled with `foo`
5. PR will not be added to project board

Sample config:
```
name: Sample config

on:
  pull_request:
    types:
      - labeled

jobs:
  add-to-project:
    name: Add PR to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/example/projects/123/views/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: foo
```
