### ISSUE TITLE
Authentication via GitHub Apps

### ISSUE THREAD

**Issue by aaronshurley** [actions/add-to-project#158]
I'm trying to set up automation for an organization project. Following [this guidance](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/automating-projects#github-actions-workflows), I would need to use a GitHub App for an organization project. Currently, this action's configuration requires a personal access token but _I don't believe_ that will provide access to an organization project. Therefore, I'm requesting the capability of authenticating via a GitHub App.

Please let me know if I have any misunderstandings. Thanks!

**Comment by peaceiris** [comment]
I also want to know what minimal permissions and scope we add to a GitHub App.

**Comment by mattcosta7** [comment]
passing this on for triage

**Comment by wadefletch** [comment]
I would also like to implement this in this way.

**Comment by camchenry** [comment]
👋 Thank you for reporting this issue! I wanted to post an update here to let you know that we are aware of this issue and have bumped it up in priority and are tracking it in our internal backlog. I'm sorry we don't have a resolution here yet (other than using a PAT), but we are looking into it, and we will post back when we have an update.

**Comment by jdbruijn** [comment]
FWIW I'm using this successfully with GitHub Apps using https://github.com/vidavidorra/github-app-token with following permissions. Example workflow: https://github.com/vidavidorra/roadmap/blob/main/.github/workflows/triage.yml.

![image](https://user-images.githubusercontent.com/62570005/187152045-b30ebb92-c541-4153-8feb-42e691b87ed9.png)


<details><summary>workflow code</summary>

```yml
name: Add issue to project
on:
  issues:
    types: opened
jobs:
  add-issue-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: vidavidorra/github-app-token
        with:
          appId: ${{ secrets.TRIAGE_APP_ID }}
          privateKey: ${{ secrets.TRIAGE_PRIVATE_KEY }}
      - uses: actions/add-to-project@a9f041ddd462ed185893ea1024cec954f50dbe42 # renovate: tag=v0.3.0
        with:
          project-url: https://github.com/orgs/vidavidorra/projects/2
          github-token: ${{ steps.generate_token.outputs.token }}
```

</details>

**Comment by jrhemstad** [comment]
I'm not sure what issues people are running into here, similar to @jdbruijn I was able to get this to work using [tibdex/github-app-token](https://github.com/tibdex/github-app-token) that is in the example docs: https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/automating-projects-using-actions#github-actions-workflows 

Full workflow: 
```
name: Add new issue/PR to project

on:
  issues:
    types:
      - opened

  pull_request_target:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue or PR to project
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@36464acb844fc53b9b8b2401da68844f6b05ebb0
        with:
          app_id: ${{ secrets.CCCL_AUTH_APP_ID }}
          private_key: ${{ secrets.CCCL_AUTH_APP_PEM }}
      - name: Add to Project
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
        uses: actions/add-to-project@a9f041ddd462ed185893ea1024cec954f50dbe42
        with:
          project-url: https://github.com/orgs/NVIDIA/projects/6
          github-token: ${{ env.TOKEN }}
```
