### ISSUE TITLE
Could not resolve to a node with the global id of '******'

### ISSUE THREAD

**Issue by defunctzombie** [actions/add-to-project#168]
I have a github workflow using this action that adds all issues with a `bug` label to my project board. I've configured the workflow in two repos with the same github token available to both (via organization secrets).

In one repo the action is working correctly. In another I am seeing this error:

```
Could not resolve to a node with the global id of '******'
```

I've hidden the _id_ value from the error cause I don't know if that's sensitive or not. The _id_ is meaningless to me and looks like some opaque identifier.

**Comment by defunctzombie** [comment]
@mattcosta7 Any thoughts on what I should try here? Or any additional info I can provide for debugging? I've got several private repos (in the same organization as my project) that fail with the same error.

**Comment by skw** [comment]
:wave: Hi @defunctzombie it sounds like for whatever reason it's having trouble resolving the graphql `node_id`.

You should be able to query the node_id directly using a GraphQL query like:

```
query getNode($node_id: ID!) { 
	node(id: $node_id) {
    id
    __typename
}
```

```
{
  "node_id": "******"
}

```

This should at least tell us the `__typename` of the node that's trying to be queried. If you can query it via GraphQL, I think it likely means that there's some kind of permission issue with the repository in question.

Thinking about this further I'm not sure how much this action supports org secrets as our docs specify using PAT, but looking at org secret creation it looks like there are a few options:

<img width="416" alt="Screen Shot 2022-08-10 at 12 36 34 PM" src="https://user-images.githubusercontent.com/113158/183990985-bf9b096e-9f72-4ff3-a372-931c382cf99f.png">

So might also want to ensure that your secret matches the expected `Repository Access` configuration.

**Comment by defunctzombie** [comment]
@skw I've double checked - our secrets (created at the org level) use the "selected repositories" option and I also confirmed they are shared with the repositories where I am seeing the error. The same secret is also shared in a repository where I use the same action but _don't_ see an error. That repository is public tho.

**Comment by jlind23** [comment]
Got the same issue on my end, repository was created a long time ago but just added automation recently. The secret is working like a charm but it seems like the action is failing with the node is.

**Comment by camchenry** [comment]
👋 We are currently working on deploying some internal security policy updates that we think might be related to this issue. We are tracking this issue in our internal backlog and we'll let you know when we have any updates.

In the meantime, for anyone who has been experiencing this issue (@defunctzombie @jlind23 @momobel), could you provide more information on your setup? The following would be helpful:

1. What type of personal access token you have configured
2. What permissions the access token has available to it
3. Any other info related to the integration: repository scope, org scope, etc.

**Comment by defunctzombie** [comment]
I've moved to a custom github bot app instead of the action because I wanted to apply these behaviors to my entire org and found the repo-by-repo approach too manual. I no longer use this action so don't have a reproduction to poke at anymore.

**Comment by jlind23** [comment]
> What type of personal access token you have configured
Not sure I get your question right. It is a personal access token created on my account and it doesn't have any expiration set.

> What permissions the access token has available to it
- All "repo" access 
- write:org and read:org
- All "user" access
- All "project" access

> Is a GitHub App token being used?
Nope

> Any other info related to the integration: repository scope, org scope, etc.
I am using the Github action with the latest version inside a private repo.

**Comment by richkuz** [comment]
I'm experiencing the same issue.

My PAT token has only the `project` and `read:project` access. The token also has SSO enabled for the `elastic` org. My GitHub action YML is defined in a private repo defined in the `elastic` org, https://github.com/elastic/. Here is the code for it:

```yml
name: Add issue to project board

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        id: add_to_project
        with:
          projectid: "PVT_kwREDACTED"
          contentid: ${{ github.event.issue.node_id }}
          query: |
            mutation add_to_project($projectid:ID!,$contentid:ID!) {
              addProjectV2ItemById(input:{projectId:$projectid contentId:$contentid}) {
                item {
                  id
                }
              }
            }
        env:
          # The default GITHUB_TOKEN env var doesn't have `project` scope.
          # The token used requires `project` scope (no other scope required).
          GITHUB_TOKEN: ${{ secrets.MY_PAT_TOKEN }}
```

The `projectId` references a V2 project defined at https://github.com/orgs/elastic/projects/

GitHub actions throws this error:

```
Error: Request failed due to following response errors:
 - Could not resolve to a node with the global id of 'I_kwDREDACTED'.
```

The same action works for me in this `public` repo in the `richkuz` org using a different PAT token with the same scope:
https://github.com/richkuz/repo1
The PAT token used in the `richkuz` org working example has no SSO configured because the `richkuz` org doesn't use SSO.

No GitHub App tokens are in use, only Personal App Tokens.
