### ISSUE TITLE
Ability to filter with label wildcards?

### ISSUE THREAD

**Issue by petemounce** [actions/add-to-project#178]
We use a hierarchical labelling system where I am. For example, `origin/customer/{name-of-customer}`, `area/product/widget-factory/windows`.

I'd really like to have closer control over how to route issues, so that I could, for example, do `label: area/product/*` and add that to the product-manager triage project, vs `area/internal/foo` to a different project.

We have quite deep hierarchies; being able to use glob semantics (`?` for wildcard single character; `*` for wildcard between `/`, and; `**` for recursively wildcard) would be extremely useful.

Is that something you would support, either by implementing directly, or by accepting an appropriate-quality-standards PR?

**Comment by skw** [comment]
:wave: Hi @petemounce this seems like a really useful improvement. Contributions are generally welcome but I'll defer to @mattcosta7 who's been owning this action 🙇

**Comment by mattcosta7** [comment]
I think we'd definitely accept regex / glob matching prs

**Comment by austenstone** [comment]
Here's some sudo code to condition on the labels with regex using [actions/github-script](https://github.com/marketplace/actions/github-script)
```yml
- uses: actions/github-script@v6
  id: my-script
  with:
    script: return context.issue.labels.reduce((p,c) => p ? p : c.match(/regex here/g), false)
- run: echo "OK"
  if: steps.my-script.outputs.result
```
