### ISSUE TITLE
Add Support for Assign and Unassign Event Types

### ISSUE THREAD

**Issue by brian-hayward** [actions/add-to-project#180]
Thank you so much for this action, it saves our team a lot of time needing to add issues to our issues board manually.

Could you consider adding _assigned_ and _unassigned_ as supported action event types? We like to automatically update the status on issues if it has been assigned or unassigned. For example, if an issue is opened by our Support team without an owner assigned, and then engineer X assigns themself as the owner, we like to automatically move that issue to "In Progress". Reversely, if they remove themself from being owner such that there are no owners, we would move it back to being "Open".

**Comment by skw** [comment]
@brian-hayward I haven't had a chance to test this yet but this may already work. Have you tried configuring your workflow with assigned/unassigned event types?

**Comment by austenstone** [comment]
Do this...
```yml
  assigned_job_beta:
    if: github.event.action == 'assigned' 
    runs-on: ubuntu-latest
    name: Add issue to project (beta)
    steps:
    - name: "Add issue that have been assigned to austenstone to project board"
      uses: actions/add-to-project@v0.3.0
      if: contains(github.event.issue.assignees.*.login, 'austenstone')
      with:
        github-token: ${{ secrets.AUSTENSTONE_ORG_REPO_TOKEN }}
        project-url: https://github.com/orgs/github/projects/5380
```

or
```yml
if: github.event.action == 'assigned' && contains(github.event.issue.assignees.*.login, 'austenstone')
```
