### ISSUE TITLE
Question about personal access token

### ISSUE THREAD

**Issue by morrowcj** [actions/add-to-project#306]
## Problem
I'm trying to implement the `add-to-project` action to an organization's repository. It appears that, in order to do so, a personal access token is required:

```yaml
# from action.yaml
github-token:
    required: true
    description: A GitHub personal access token with write access to the project
```

However, I don't fully understand how to store a PAT in an organization's secret variables. Does the "value" field of the secret variable actually need to be a PAT for this action to work? Since organizations aren't able to generate PATs, does one member of the org need to be responsible for generating and maintaining the token?
