### ISSUE TITLE
PR not being added to project when created

### ISSUE THREAD

**Issue by CalvinWilkinson** [actions/add-to-project#369]
### **Description:**
I have created 2 new workflows for my repository.  The intent is for both of them use this GitHub action to automatically add the issue or PR to my organizational project when the issue or PR is created.
The add issue workflow works just fine.
The add PR workflow does not trigger even though I have the correct trigger for the workflow setup.

### **Expected Behavior:**
The workflow automatically triggers when creating a new PR.

### **Workflows Being Used:**

✅This workflow is for adding issues and works fine.
```yml
name: ⚙️Add Issue To Org Project


on:
  workflow_dispatch:
  issues:
    types: 
      - opened


jobs:
  testing:
    name: testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/add-to-project@v0.5.0
      with:
        project-url: https://github.com/orgs/KinsonDigital/projects/11
        github-token: ${{ secrets.CICD_TOKEN }}
        label-operator: NOT
```

❌This workflow is for adding pull requests and _**DOES NOT**_ work.
```yml
name: ⚙️Add PR To Org Project


on:
  workflow_dispatch:
  pull_request:
    types: 
      - opened


jobs:
  testing:
    name: testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/add-to-project@v0.5.0
      with:
        project-url: https://github.com/orgs/KinsonDigital/projects/11
        github-token: ${{ secrets.CICD_TOKEN }}
        label-operator: NOT
```
