### ISSUE TITLE
Could not resolve to a ProjectV2 with the number 3.

### ISSUE THREAD

**Issue by Mittelblut9** [actions/add-to-project#411]
Im currently getting this error.

```bash
Error: Request failed due to following response errors:
 - Could not resolve to a ProjectV2 with the number 3.
 ```
 
 My workflow looks like:
 ```yml
 jobs:
    add-to-project:
        name: Add issue to project
        runs-on: ubuntu-latest
        steps:
            - uses: actions/add-to-project@v0.5.0
              with:
                  project-url: https://github.com/orgs/{org}/projects/3
                  github-token: ${{ secrets.MY_SECRET }}
 ```
 
 * The Project link is valid and the secret too.
