### ISSUE TITLE
dependabot labeled PRs do not add to project

### ISSUE THREAD

**Issue by gkwan-ibm** [actions/add-to-project#518]
I created a action:

```
name: Add PRs to Dependabot PRs dashboard

on:
  pull_request:
    types:
      - labeled

jobs:
  add-to-project:
    name: Add PR to dashboard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/...
          github-token: ${{ secrets.ADMIN_BACKLOG }}
          labeled: dependencies
```

This action works to add the PR to the project if I manually add the `dependencies` label.
But, the dependabot created PRs (the Bump PRs) do not automatically add to the project.

**Comment by gkwan-ibm** [comment]
Seems to be this reason.
```
Error: Input required and not supplied: github-token
```

**Comment by gkwan-ibm** [comment]
The dependabot creates branch and PR in the repo, not from a fork, why the above action does not work?

**Comment by surchs** [comment]
from the docs: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow

> When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN, with the exception of workflow_dispatch and repository_dispatch, will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs. For example, if a workflow run pushes code using the repository's GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur.

So if you want to respond to events that are triggered by bots you have two options:
- use a personal access token so the event is triggered by you (not the bot)
- look for the output of the bot action at a regular interval https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

**Comment by gkwan-ibm** [comment]
The token I used is my personal token. Again, manually label PR works fine.

The question is "Why the dependabot labeled PRs (the Bump PRs) does not work?"

**Comment by surchs** [comment]
> The token I used is my personal token

ah, my bad

> Why the dependabot labeled PRs (the Bump PRs) does not work?

you cannot have a bot apply a label and then have the https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=labeled#pull_request event trigger another workflow. So likely your issue is that the label is applied by dependabot. Our workaround is as I mentioned to have a cron job do this: https://github.com/neurobagel/planning/blob/main/.github/workflows/global_move_bot_pr_to_board.yml

**Comment by gkwan-ibm** [comment]
How's about `opened`? I tried it and also not work. Same reason?

```
on:
  pull_request:
    types:
      - opened
 ```

**Comment by mikebell** [comment]
@surchs did you find another solution to this? I had a look round some of the neurobagal repos and I can see your not using it anymore. Did it not work as expected? I'm currently trying find a solution to adding dependabot prs from around 20-30 repos to a project.

**Comment by marywhite** [comment]
👋🏻 You should be able to add an opened trigger that works with dependabot PRs:

```yml
on:
  pull_request:
    types:
      - opened
 ```   

The issue is that only dependabot secrets are available in an actions workflow triggered by dependabot. A solution for this is to store a dependabot secret with the same name as the action secret used for the workflow. A good resource for troubleshooting dependabot in actions can be found here: [ADD_TO_PROJECT_PAT](https://docs.github.com/en/code-security/dependabot/troubleshooting-dependabot/troubleshooting-dependabot-on-github-actions#accessing-secrets)

Good luck, and feel free to reach out again if you continue having issues.
