### ISSUE TITLE
Adding status and start or end date

### ISSUE THREAD

**Issue by mireklzicar** [actions/add-to-project#602]
What do you think about being able to specify some defaults in terms of project status and start or end date? The usage could be:
```
      with:
          project-url: https://github.com/orgs/<orgName>/projects/<projectNumber>
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: bug, needs-triage
          label-operator: NOT
          status: Backlog
          start_date: now
          due_date: 7
```
This would add automatically new issues into specific project board column (such as Backlog) with start date as today and due date in 7 days.
