### ISSUE TITLE
how to add to project without workflow

### ISSUE THREAD

**Issue by quantuminformation** [actions/add-to-project#661]
You prefer not to use workflows, 

but using this:
```yml
name: Auto apply triage label and default project

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  label_and_assign_project:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      repository-projects: write  

    steps:
      - name: Add "triage" label if no milestone
        if: ${{ github.event.issue.milestone == null }}
        run: |
          gh issue edit ${{ github.event.issue.number }} \
            --repo quantumjs/launch-track \
            --add-label triage
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}



      - name: Add issue to org-level project
        run: gh project item-add quantumjs/1 --content-id "${{ github.event.issue.node_id }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
gives [error](https://github.com/quantumjs/launch-track/actions/runs/12769275090/job/35591493286):

<img width="806" alt="Image" src="https://github.com/user-attachments/assets/b387bcb8-abf0-4087-89b3-791ce6b66c55" />
