### ISSUE TITLE
Enable add-to-project to add issues to a specific status / column in the project

### ISSUE THREAD

**Issue by stuart-leitch** [actions/add-to-project#71]
Thanks so much for this action, it's a great help with making sure that new issues land on my team's board for visibility.

It would be great if we could also specify the status (board column) that the issue should be added to.  For example, we have an 'Inbox' column where new issues go for triage.

**Comment by kalgurn** [comment]
Hi @stuart-leitch, it's doesn't seems like the API itself supports such kind of functionality https://docs.github.com/en/graphql/reference/input-objects#addprojectnextiteminput

As a workaround I can suggest to use a custom action for this particular use case. 
I've made [one](https://github.com/marketplace/actions/update-github-project-beta-item-status) derived from the add-to-project action, feel free to fork/use/contribute

**Comment by mattcosta7** [comment]
> Thanks so much for this action, it's a great help with making sure that new issues land on my team's board for visibility.
> 
> It would be great if we could also specify the status (board column) that the issue should be added to. For example, we have an 'Inbox' column where new issues go for triage.

@stuart-leitch sorry for the late reply here - would the `Item added to project` workflow help that use case, without needing to handle it from the action

https://user-images.githubusercontent.com/8616962/169136067-7904aa3c-8fad-4472-8365-4814342e5f61.mov

Agreed that supporting more granular scenarios here might be helpful for some usecases, but for adding a default value to incoming items in a non-granular way, that should be a good step

**Comment by OliverRC** [comment]
For custom columns it looks like you could possibly update the item after it is added to the project:
https://docs.github.com/en/issues/trying-out-the-new-projects-experience/using-the-api-to-manage-projects#updating-a-custom-text-number-or-date-field
https://docs.github.com/en/issues/trying-out-the-new-projects-experience/using-the-api-to-manage-projects#updating-a-single-select-field

**Comment by dtzar** [comment]
The workflow option is nice, but I still believe there would be value added by having an option to configure this from the GitHub action because:
1. There are a number of use cases where you would want specific tags to be added only when done via the action (versus all new issues added to the project.
2. Currently, GitHub workflow on beta projects doesn't allow any customization of the "Item added to project" workflow.  You can only add the status label with one of the pre-defined values there.

**Comment by ezio-melotti** [comment]
It would really be useful if there was a way to set custom fields, and even more useful if this could be done conditionally depending on what label triggered the action (and/or possibly other factors).

---

For example, I have a project to track release/deferred blockers, with the default `status` field and a custom `type` field.  When an issue is labeled as either `release-blocker` or `deferred-blocker`, I want to:
* unconditionally set the `status` field to be set to `todo`
* conditionally set the `type` field to either `Release blocker` or `Deferred blocker`. 

I also want the `type` to be updated if the issue is re-labeled (e.g. a `deferred-blocker` that becomes a `release-blocker`).  This could be implemented with something like:
```yml
name: Update GH projects

on:
  issues:
    types:
      - labeled

jobs:
  add-to-project:
    name: Add to the Release and Deferred Blocker project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.1.0
        with:
          project-url: https://github.com/orgs/python/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: release-blocker, deferred-blocker
          label-operator: OR
          # set project fields (syntax is made up to illustrate the idea)
          set-field:
            # unconditionally set the `status` field to `todo`
            status: todo
          set-field:
            # if the issue was labeled `release-blocker`, set the `type` field too
            if: github.action.event.label == "release-blocker"
            type: Release blocker
          set-field:
            # if the issue was labeled `deferred-blocker`, set the `type` field too
            if: github.action.event.label == "deferred-blocker"
            type: Deferred blocker
```
This will unconditionally set the `status` field on the project to `todo`, and conditionally set the `type` field to `Release blocker` or `Deferred blocker` depending on the label that triggered the `labeled` event.

---

If there was only an unconditionally way to set custom fields, the same result could be achieved by creating a separate step for each label, e.g.:
```yml
          # (set-field syntax is made up to illustrate the idea)
          labeled: release-blocker
          set-field:
            status: todo
            type: release-blocker
          ...
          labeled: deferred-blocker
          set-field:
            status: todo
            type: deferred-blocker
```

If you prefer, I can create a separate issue about conditional addition, assuming a way to set (custom) fields is going to be added to the action.

**Comment by Hafnernuss** [comment]
> Hi @stuart-leitch, it's doesn't seems like the API method AddProjectNextItem supports such kind of functionality https://docs.github.com/en/graphql/reference/input-objects#addprojectnextiteminput
> 
> As a workaround I can suggest to use a custom action for this particular use case. I've made [one](https://github.com/marketplace/actions/update-github-project-beta-item-status) derived from the add-to-project action, feel free to fork/use/contribute

Unfortunately, this does not seem to work (anymore?), and this is also a feature I would find highly useful for the already stated reasons. 
We would like to sort new issues according to their labels (bug, feature request) into seperate columns in our project board.

**Comment by jeherve** [comment]
> Unfortunately, this does not seem to work (anymore?)

The examples above use the `[ProjectNext](https://docs.github.com/en/graphql/reference/objects#projectnext)` object, which can only be used with the old "Classic" GitHub projects, while this action is now compatible with the new GitHub Projects. You'll consequently want to use the new [ProjectV2](https://docs.github.com/en/graphql/reference/objects#projectv2) object and mutations instead.

For our particular needs in this issue, we'd need:

- [the ProjectV2 object](https://docs.github.com/en/graphql/reference/objects#projectv2) and its fields to fetch information about the different columns available in the project board.
- [the updateProjectV2ItemFieldValue mutation](https://docs.github.com/en/graphql/reference/mutations#updateprojectv2itemfieldvalue) to move issues to a specific column on the project.

**Comment by ishowta** [comment]
There are Github Actions to solve exactly this problem, and I used them. 🙏
https://github.com/titoportas/update-project-fields

**Comment by dgwyer** [comment]
For anyone else that needs to add an issue to a custom default column in a project (i.e. other than 'Todo'), you can do this directly via the project UI. **You don't need to add anything else to your YAML workflow file to get this to work.**

I used the [Add To GitHub Projects](https://github.com/marketplace/actions/add-to-github-projects) action, and then in the project UI simply specified [which column to use as the default](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/quickstart-for-projects#configure-built-in-automation)!

**Comment by bradtaniguchi** [comment]
> I used the [Add To GitHub Projects](https://github.com/marketplace/actions/add-to-github-projects) action to assign newly opened issues to the project. And then in the project UI simply specified [which column to use as the default](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/quickstart-for-projects#configure-built-in-automation)!

I honestly forgot the workflows tab existed! Last I checked it was still under construction and thus disabled. Glad to see it can handle the use-case without much fussing around. 😄

**Comment by dgwyer** [comment]
> I honestly forgot the workflows tab existed! Last I checked it was still under construction and thus disabled. Glad to see it can handle the use-case without much fussing around. 😄

Yes, it would be super useful if this info was added to the GitHub action readme docs!

**Comment by mattcosta7** [comment]
> > I honestly forgot the workflows tab existed! Last I checked it was still under construction and thus disabled. Glad to see it can handle the use-case without much fussing around. 😄
> 
> Yes, it would be super useful if this info was added to the GitHub action readme docs!

Happy to accept PRs for it!

**Comment by ezio-melotti** [comment]
Unless I'm missing something, the solution suggested in #282 doesn't solve the issue.

The "Item added to project" workflow only works for the default "Status" column, and the [documentation linked in the PR](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/quickstart-for-projects#configure-built-in-automation) doesn't explain how to use a different column:
![image](https://user-images.githubusercontent.com/25624924/207674974-94ec5a5a-a738-4247-8cf4-d3400cfbc6e1.png)

Currently it's still not possible to:
- [ ] set the value for a column that is not "Status"
- [ ] set the value when an issue is updated, rather than just added
- [ ] set multiple values (e.g. `Status` and `Type`)
- [ ] set values conditionally (e.g. set the `Type` based on a label)

(See https://github.com/actions/add-to-project/issues/71#issuecomment-1184599870 above for more context.)

In addition, if this is handled from the project workflow instead of the action, each individual project would need to be updated manually.

I would recommend to:
* update the documentation to explain how to set a different column (if at all possible)
* reopen this issue to track and implement the features listed above

**Comment by mattcosta7** [comment]
Sorry, closed this by merging the docs update, but meant to reopen for future improvements.  thanks for calling it out

**Comment by Snailedlt** [comment]
@mattcosta7 Seems like @OliverRC's solution solves the issue of adding to a specific column. If it does, then it could be added to this action.

I'm thinking something like this could be added:
```yml
name: Add issues to project columns based on issue events

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issues to project
    runs-on: ubuntu-latest
    steps:
      - name: Add new issues to project column 'Todo'
        uses: actions/add-to-project@v0.5.0
        if: github.event.action == 'opened'
        with:
          project-url: https://github.com/orgs/<orgName>/projects/<projectNumber>
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          column-name: Todo

      - name: Move assigned issues to 'In Progress' column in project
        uses: actions/add-to-project@v0.5.0
        if: github.event.action == 'assigned'
        with:
          project-url: https://github.com/orgs/<orgName>/projects/<projectNumber>
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          column-name: Done

      - name: Move closed issues to 'Done' column in project
        uses: actions/add-to-project@v0.5.0
        if: github.event.action == 'closed'
        with:
          project-url: https://github.com/orgs/<orgName>/projects/<projectNumber>
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          column-name: Done
```

If `column-name` has a value we run @OliverRC's script after the issue has been added to the project.

Or maybe we want a totally new action called `move_column_in_project` to isolate the two?
